### PR TITLE
🚀 Performance improvements (ListView, ColumnView, ItemView, DynamicImage)

### LINKED ISSUE #90: [perf] Ensure correct usage of `ListView`
The current usage of `ListView` is problematic, as it essentially loads all elements inline. This is the main reason the app feels *very* slow.

We should take an approach similar to Spot, as explained here: https://discourse.gnome.org/t/a-listview-with-a-header-and-footer/19234

Even pages like Library Songs, Library etc... have a Paginator and sort box at the top, we should possibly add those in the Adw.ToolbarView and as last child respectively.

Also investigate ways to make the History page work without causing trouble.

### PR DESCRIPTION
**Pull request by vixalien**
## ~ScrollableView~ AnnotatedScrollableView

Previously, When you were looking at a playlist or another list with many items, Muzika would become unresponsive because it was rendering all the (play)list items at once.

Now, with the help of a new custom widget that loads list items as needed, even when the page has a header and a footer, which are `unmap`ed and `map`ed when needed.

This is solved by introducing a new widget that allows a scrollable view to have a header and footer, all while being scrollable.

Here is a video to demonstrate what I'm saying. Note that only the widgets currently in view are mapped, others are unmapped (here shown with a faded colour) (Don't mind the new GTK renderer artefacts):

https://github.com/vixalien/muzika/assets/37999241/47486179-84f6-41a8-8f3a-b69487f91f51

- [x] Rename `ScrollableView` to `AnnotatedScrollableView`

## ListView/ColumView

- [x] Don't use `notify` on all items to reload property data.
- [x] Connect self's notify handlers in `setup` instead of `bind`

## ItemView

- [x] Make the `PlaylistItemView` scrollable, automatically passing the relevant data to the inner view.
- [x] Should set the multi-select model directly instead of getting one on the fly

## ColumnView

- [x] Investigate using construct time properties (https://gitlab.gnome.org/GNOME/gjs/-/issues/615)
- [x] Split all the columns into their files to reduce clutter

## DynamicImage

The big refactoring™ should be started because this widget slows up everything.

- [ ] Initialize all the children initially
- [ ] Make this extend a `GtkWidget`
- [ ] Use a singular `GtkButton` for play/pause buttons.

fix #90

### CODE REVIEW

**Comment by vixalien** [comment]
It turns out there is only so much we can do. The ListView implementation is heavily flawed and renders 200 items at once initially instead of rendering the items currently in view.

https://gitlab.gnome.org/GNOME/gtk/-/issues/6409

**Comment by vixalien** [comment]
I just updated this PR and think it's ready for final cleanups before merge. If you are watching this 👀, please install the latest flatpak build to help test this.

When merged, this will be one of the largest PRs and will bring an improved codebase to Mzk.

**Comment by gregthwuen** [comment]
I have been using this branch for the past few days and overall the UI just feels much smoother than before. However, I have also noticed a few bugs where I am unsure whether these are regressions. Do you know any way I could quickly test two builds side-by-side?

Either way, I'll report the bugs when I find some time, hopefully tomorrow :)

**Comment by vixalien** [comment]
> However, I have also noticed a few bugs

Good. There has been a bug in this PR where scrolling seemed inconsistent but I have fixed that, you might need to update the build.

> I am unsure whether these are regressions.

You can still report all bugs and I could fix even the non-regression ones.

> Do you know any way I could quickly test two builds side-by-side?

Not sure.

**Comment by vixalien** [comment]
Hello. Did you get time to test?

**Comment by gregthwuen** [comment]
Yes, at least I don't experience the graphical glitches when scrolling a list anymore.

**Pull request merged**
