### PR TITLE
UI: Mark a lot of strings translatable

### PR DESCRIPTION
**Pull request by sabriunal**
**UI: Mark a lot of strings translatable**

**Add Turkish translation**

### CODE REVIEW

**Comment by vixalien** [comment]
this will probably have to wait for the blueprint transition #4 

or I'll have to merge this before, then rework the blueprint transition

**Comment by sabriunal** [comment]
I'll rework after the blueprint transition. No problem for me.

**Comment by vixalien** [comment]
great. thanks though for your amazing work.

**Comment by vixalien** [comment]
rebase main please (and possibly check for new files without translations)

**Comment by sabriunal** [comment]
Rebaset without Turkish translation.

**Comment by vixalien** [comment]
this is superseded by #14 

let's shift focus to that PR

**Pull request closed without merging**
