### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by kianmeng**
found via `codespell -S *.lock,*.json -L trough`

### CODE REVIEW

**Comment by vixalien** [comment]
hey. could you care to add your name to

https://github.com/vixalien/muzika/blob/e57d456654ff2a1346f284f77b345f1bd7404d0a/src/application.ts#L59-L62

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

**Comment by vixalien** [comment]
give me your name (and email if you wish) and I'll add you

**Comment by kianmeng** [comment]
> give me your name (and email if you wish) and I'll add you

you can get the details from my git commit. Thanks.

**Pull request merged**
