### PR TITLE
i18n: Add Turkish translation

### PR DESCRIPTION
**Pull request by sabriunal**

### CODE REVIEW

**Comment by vixalien** [comment]
please rebase

**Comment by vixalien** [comment]
I've rebased for you, please add the missing translations

**Comment by sabriunal** [comment]
Rebased.

**Comment by vixalien** [comment]
fixed some things, please rebase main

**Comment by sabriunal** [comment]
rebased

**Comment by vixalien** [comment]
you might want to rebase again since I just merged your other PR :)

**Comment by sabriunal** [comment]
Rebased. No problem for me :)

**Review by vixalien — APPROVED** [review]

**Pull request merged**
